dataset:
  root: "/mnt/data_hdd/Dataset/carlascene_dataset"
  version: "v1.14"

client:
  host: 127.0.0.1
  port: 2000
  time_out: 1000.0

sensors:
  !include ./configs/sensors.yaml

categories:
  !include ./configs/categories.yaml

attributes:
  !include ./configs/attributes.yaml

visibility:
  !include ./configs/visibility.yaml 

scene_count: 1

worlds:  #map
  - 
    map_name: "Town01"
    map_category: "semantic_prior"
    settings:
      fixed_delta_seconds: 0.01
    captures: #log
      - 
        date: "2023-01-09"
        time: "10-45-20"
        timezone: "+0800"
        capture_vehicle: "c0003"
        location: "Town01"
        scenes:
          - 
            custom: False
            collect_time: 20
            keyframe_time: 0.5
            ego_bp_name: "vehicle.tesla.model3"
            calibrated_sensors:
              !include ./configs/calibrated_sensors.yaml
            description:
              "Town01"
  - 
    map_name: "Town02"
    map_category: "semantic_prior"
    settings:
      fixed_delta_seconds: 0.01
    captures: #log
      - 
        date: "2023-01-11"
        time: "10-45-20"
        timezone: "+0800"
        capture_vehicle: "c0003"
        location: "Town02"
        scenes:
          - 
            custom: False
            collect_time: 20
            keyframe_time: 0.5
            ego_bp_name: "vehicle.tesla.model3"
            calibrated_sensors:
              !include ./configs/calibrated_sensors.yaml
            description:
              "Town02"
  - 
    map_name: "Town03"
    map_category: "semantic_prior"
    settings:
      fixed_delta_seconds: 0.01
    captures: #log
      - 
        date: "2023-01-12"
        time: "10-45-20"
        timezone: "+0800"
        capture_vehicle: "c0003"
        location: "Town03"
        scenes:
          - 
            custom: False
            collect_time: 20
            keyframe_time: 0.5
            ego_bp_name: "vehicle.tesla.model3"
            calibrated_sensors:
              !include ./configs/calibrated_sensors.yaml
            description:
              "Town03"
  - 
    map_name: "Town04"
    map_category: "semantic_prior"
    settings:
      fixed_delta_seconds: 0.01
    captures: #log
      - 
        date: "2023-01-13"
        time: "10-45-20"
        timezone: "+0800"
        capture_vehicle: "c0003"
        location: "Town04"
        scenes:
          - 
            custom: False
            collect_time: 20
            keyframe_time: 0.5
            ego_bp_name: "vehicle.tesla.model3"
            calibrated_sensors:
              !include ./configs/calibrated_sensors.yaml
            description:
              "Town04"
  - 
    map_name: "Town05"
    map_category: "semantic_prior"
    settings:
      fixed_delta_seconds: 0.01
    captures: #log
      - 
        date: "2023-01-15"
        time: "10-45-20"
        timezone: "+0800"
        capture_vehicle: "c0003"
        location: "Town05"
        scenes:
          - 
            custom: False
            collect_time: 20
            keyframe_time: 0.5
            ego_bp_name: "vehicle.tesla.model3"
            calibrated_sensors:
              !include ./configs/calibrated_sensors.yaml
            description:
              "Town05"
  - 
    map_name: "Town06"
    map_category: "semantic_prior"
    settings:
      fixed_delta_seconds: 0.01
    captures: #log
      - 
        date: "2023-01-21"
        time: "10-45-20"
        timezone: "+0800"
        capture_vehicle: "c0003"
        location: "Town06"
        scenes:
          - 
            custom: False
            collect_time: 20
            keyframe_time: 0.5
            ego_bp_name: "vehicle.tesla.model3"
            calibrated_sensors:
              !include ./configs/calibrated_sensors.yaml
            description:
              "Town06"
  - 
    map_name: "Town07"
    map_category: "semantic_prior"
    settings:
      fixed_delta_seconds: 0.01
    captures: #log
      - 
        date: "2023-01-22"
        time: "10-45-20"
        timezone: "+0800"
        capture_vehicle: "c0003"
        location: "Town07"
        scenes:
          - 
            custom: False
            collect_time: 20
            keyframe_time: 0.5
            ego_bp_name: "vehicle.tesla.model3"
            calibrated_sensors:
              !include ./configs/calibrated_sensors.yaml
            description:
              "Town07"        
  - 
    map_name: "Town10HD"
    map_category: "semantic_prior"
    settings:
      fixed_delta_seconds: 0.01
    captures: #log
      - 
        date: "2023-01-22"
        time: "10-45-20"
        timezone: "+0800"
        capture_vehicle: "c0003"
        location: "Town10HD"
        scenes:
          - 
            custom: False
            collect_time: 20
            keyframe_time: 0.5
            ego_bp_name: "vehicle.tesla.model3"
            calibrated_sensors:
              !include ./configs/calibrated_sensors.yaml
            description:
              "Town10HD"              
          